const HOST = 'https://192.168.10.53'
const WSS = 'wss://192.168.10.53'
const CLIENT_PORT = '8086'
const SERVER_PORT = '4000'
const PRODUCTION_PORT = '443'
const GRAPHQL_ENDPOINT = 'graphql';
const HOST_NAME_PRODUCTION = 'unicron.com';
const HOST_NAME_DEV = 'localhost';
const MONGODB_PATH = 'mongodb://localhost/TripleD'
module.exports.MONGODB_PATH = MONGODB_PATH
module.exports.HOST_NAME_DEV = HOST_NAME_DEV
module.exports.HOST_NAME_PRODUCTION = HOST_NAME_PRODUCTION
module.exports.HOST = HOST
module.exports.WSS = WSS
module.exports.PRODUCTION_PORT = PRODUCTION_PORT
module.exports.CLIENT_PORT = CLIENT_PORT
module.exports.SERVER_PORT = SERVER_PORT
module.exports.GRAPHQL_ENDPOINT = GRAPHQL_ENDPOINT